### ISSUE TITLE
Allow presenter to set a "note"?

### ISSUE THREAD

**Issue by soichih** [datalad-datasets/ohbm2020-posters#127]
I've seen some presenter leaving the chat session opened with a note saying something like 

> Thank you for visiting. I will be online to discuss with you at 6:00 UTC

via presenter writing something on the screen and screensharing it (and leave the video chat running). 

I think it would be great if we could something similar through our dashboard.. although I am not sure how to do anything like that.

**Comment by yarikoptic** [comment]
yeah, would be nice -- but I have not found any "ready" solution for jitsi yet ... not sure if mattermost wouldn't blow up with some 2k threads/rooms being added.  some other solution is needed. E.g. we could pre-mint some URLs on some other crowd note taking etc website.  It would be separate from jitsi.  I wonder if we could "inject" messages into jitsi chat upon initial login (when we know that the count is 0) to at least announce to use that chat instead of built-in

**Comment by yarikoptic** [comment]
Hey -- what about etherpad? I have not used it actively but people do!  Should be easy to premint all pages like https://etherpad.wikimedia.org/p/OHBM2020-1-comments .  There might be an API to initiate them all nicely and consistently and fetch into a git repo alongside the PDFs? (that one is coming shortly)

**Comment by yarikoptic** [comment]
everything needed seems to be possible according to the docs: https://etherpad.org/doc/v1.7.0/#index_what_can_i_do_with_this_api

**Comment by yarikoptic** [comment]
re jitsi: 
-  may be we could adjust our JS where we start the room to listen on the chat messages and archive them in the etherpad?  https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe says that it is possible to add event notification on endpointTextMessageReceived  .

The only immediate "problem" I see, since there is no "authoritive visitor" -- is that not everyone probably should listen on them and send to wss? or may be all could and wss would remove duplicates (e.g. by adding a time stamp and then comparing with some jitter allowed?)

jitsi also has `api.executeCommand('sendEndpointTextMessage', 'receiverParticipantId', 'text');` but I don't know if that could be used to send to everyone to announce that there is etherpad logging "on" and give url. 

But there is `api.executeCommand('subject', 'New Conference Subject');` so may be we could add that there?

**Comment by soichih** [comment]
Oh~ etherpad looks very useful!

So.. are you thinking something like displaying the etherpad below the
jitsi video? I think we can put pdf and etherpad together to make it look
like this

[image: image.png]

**Comment by soichih** [comment]
Oh, and there is also a chat built into etherpad!

![image](https://user-images.githubusercontent.com/923896/86173541-21c89e00-baee-11ea-976b-3ca77eba89d5.png)

I can prototype this in like 10 minutes.. should I?

**Comment by soichih** [comment]
And we could *disable* chat on the jitsi (to encourage people to use etherpad)?

**Comment by yarikoptic** [comment]
Some PDFs on some systems mightn't load into. Screen share navigation by speaker might be more useful. But if all those panes could collapse or resize - perfect!
Also there is still emoticons to be added/merged... May be that pane could control what to see... You know better :-)

**Comment by soichih** [comment]
Oh, I see. I didn't think about presenters sharing the screen. Or even the
visitors. Yeah, we could add splitter so they can control what to see..

**Comment by effigies** [comment]
This is achieved with etherpad. There are other issues for modifying configuration or enabling alternatives, so I will close this.
