### ISSUE TITLE
Bunch of wrong attendance numbers

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#154]
I think nobody is in any room, but we have non 0 counts. Hard reset to 0?

**Comment by soichih** [comment]
They are non-0 because we are receiving keepalive from various users still. If we reset them to 0, it will just go right back again. We also have code that automatically purges stale client IDs. So if client fails to send the jitclose, it should be removed within 60 seconds. 

I am hoping that.. with PR #150, once *everyone* refreshes their pages, we should no longer see those phantom counts - caused by someone having a tag / page opened with closed jitsi sessions. But the time will tell. 

Oh.. and I need to have @r03ert0 make similar update on brainweb version.. the counts might be coming from theirs if they haven't updated it.

**Comment by soichih** [comment]
Might be caused by #153

**Comment by r03ert0** [comment]
done!

**Comment by soichih** [comment]
@r03ert0 

I just submitted this PR
> https://github.com/datalad-datasets/ohbm2020-posters/pulls

I've made quite a bit of changes to room.html.. but basically, you can now send the actual count of participants as reported by the jitsi API (`api.getNumberOfParticipants()`) and if this is set, the server side will trust it as the actual participant count (ignore the unique IP list). This allows us to accurate report the number of participants including people who didn't join through our web Apps.

Another important update is that, the room.html will now only start sending keepalive *after* jitsi client is actually opened (`videoConferenceJoined` event). On mobile phone, user is given a chance to choose between web version and the App version. If the user sits there without making a decision, the count should not increase, and I believe this was happening on some cases. 

I've also made various Vue related updates.. which makes it harder to read the code if you are not familiar with Vue.. but I apologize if that is the case!

**Comment by yarikoptic** [comment]
I think @soichih has addressed many possible use cases and numbers became much more robust etc. Closing
