### ISSUE TITLE
Link Broken: Poster 1057

### ISSUE THREAD

**Issue by vasudev-sharma** [datalad-datasets/ohbm2020-posters#184]
Hi,

I'm the co-author of the **Poster - 1057** titled (_AxonDeepSeg: Automatic Myelin and Axon Segmentation Using Deep Learning_) and trying to access the [link](https://cdn-akamai.6connex.com//645/1827//ohbm2020_boudreau_FINAL_15921677822526191.pdf) as mentioned [here](https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/OHBM%202020%20Poster%20Numbering%20-%20AbstractsAdHocReport_2015_20200.tsv). The link seems to be broken. See the screenshot below:
![image](https://user-images.githubusercontent.com/31419210/149258527-c60d33bf-86a2-4b46-82f9-b85562b2921a.png)

Is there any resolution for the same?

**Comment by effigies** [comment]
Nope. These were links into the ohbm-hosted poster site unless the authors provided an alternative. We didn't host the posters ourselves.

**Comment by yarikoptic** [comment]
yes, unfortunately, as @effigies has mentioned we do not host/provide posters. I believe I have an archival copy of them somewhere though, but since "re-sharing" was not explicitly provisioned in terms of upload of posters to OHBM platform, can't reshare.

It might be worthwhile though to direct inquiry to OHBM committee to see if they do/can provide historical copies of the posters -- we could then adjust urls to point to new location(s).  Wanna to take the lead on that @vasudev-sharma ?

**Comment by vasudev-sharma** [comment]
Thanks @yarikoptic @effigies  for the response. I will get in-touch with OHBM commitee for the same and will let you know the reply.

**Comment by vasudev-sharma** [comment]
Unfortuantely, that's not possible. Hence, I'm closing the issue.
