### ISSUE TITLE
visitors counter resets to 0

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/ohbm2020-posters#58]
attn @soichih :  we deployed, counter did go to 1 (whenever only I joined), but never went higher and then got to 0  whenever others have joined.  We are still in gather.town by the pool if you decide to hangout with testing users ;)

**Comment by soichih** [comment]
Oops.. that's an embarrassing bug.. I've fixed it!

**Comment by yarikoptic** [comment]
Straight in master or backend script fix coming as a PR?

**Comment by soichih** [comment]
The backend fix is already in place .. as it's just running on my dev server. 

Actually, something is still not right about something.. I will have a look later tonight.

**Comment by yarikoptic** [comment]
But please send changes later on here as well, happen we decided to deploy it centrally

**Comment by soichih** [comment]
I've included the service side bug fixes with this PR https://github.com/datalad-datasets/ohbm2020-posters/pull/61

I couldn't recreate the problem I was seeing earlier. I think everything is good to go with this PR.

**Comment by yarikoptic** [comment]
It seems it resets to 0 also when I simply reload the https://datalad-datasets.github.io/ohbm2020-posters/ page after going to some room, having it increment to 1, then reload the page -- count disappears.

**Comment by soichih** [comment]
The way that we are tracking the visitor count is by monitoring when a user open a room from the list page, and monitoring if the room is closed or not. To handle a situation when someone closes the whole browser, I've added `beforeunload` hook so that it will mark those opened room as closed (as it will close the opened room as well) so that counter won't get stuck (although we have serverside code to remove old IPs). Of course, the issue is then what we should do if someone just closes the list page - but not the room.. (such as in your case..) Humm..

Oh. maybe we could open a jitsi within a <iframe> so that we can inject the monitoring that goes along with the actual jitsi page. This will be pretty rock solid, I think.. as list page doesn't have to keep up with who is opened / closed. What do you think?

**Comment by soichih** [comment]
Looks like this approach works! I will get it implemented. I will also update the server side to work on the session id (page id actually).

**Comment by effigies** [comment]
I think this is resolved?

**Comment by yarikoptic** [comment]
I think so too. @soichih - please add "Closes #" statements in the commits or PRs which resolve a known to you issue. Cheers!
